#-------------------------------
# Site Settings
title: Danny Ebanks
logo: '/images/logo.svg' # You can add own logo. For example '/images/logo.png'.
description: Danny Ebanks' Personal Website
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Research Projects'
      url: '/ResearchProjects/'
    - title: 'About'
      url: '/about/'
    - title: 'CV'
      url: '/cv/'
  #  - title: 'Videos'
  #    url: '/videos/'
    - title: 'More'
      submenu:
    #  - url: '/about/'
    #    title: 'About'
      - url: '/contact/'
        title: 'Contact'
     # - url: '/elements/'
     #   title: 'Elements'


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Danny Ebanks
  hero__description: Political Methodology, Statistics, Machine Learning, American Politics
  hero__image: '/images/IMG_1634.png' # You can add hero image. For example '/images/06.jpg'


#-------------------------------
# Author Global Settings
author:
  author__name: Danny Ebanks
  author__bio: Postdoctoral Fellow, IQSS at Harvard
  author__avatar: /images/IMG_2236.png


#-------------------------------
# Blog Section Settings
blog__settings:
  enable: true
  blog__title: Latest Papers
  blog__description:


#-------------------------------
# Videos Section Settings
videos__settings:
  enable: false
  videos__title: Latest Videos
  videos__description:


#-------------------------------
# Tag Section Settings
tag__settings:
  enable: true
  tag: electoral systems # To display the tag section, specify your favorite tag.


#-------------------------------
# Author Section Settings
author__section:
  enable: true
  author__section__title: I am a Postdoctoral Fellow for IQSS at Harvard. 
  author__section__description: I recently earned my PhD at Caltech in Quantitative Social Sciences, where I developed my research interests in Political Methodology, American Politics and Congress. My research focuses on latent variable models, Bayesian statistics, legislatures, and natural language processing. I strive to develop and implement statistical methods, to understand the latest in machine learning and AI, and innovate in these areas in ways small  and large to better understand our political world.  I am always eager to chat about research and statistics, so feel free to reach out. Outside of research, I'm lifelong runner who hails from New York.
  aurhor__section__button__text: Job Market Paper
  aurhor__section__button__link: /files/topic_consist.pdf
  author__section__big__image: /images/IMG_0663.png
  author__section__small__image: /images/IMG_2236.png


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  enable: false
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address
  mailchimp__button__text: Subscribe
  mailchimp__background__image: /images/subscribe-bg.jpg


#-------------------------------
# Footer Settings
footer__description: Political Methodology, Statistics, Machine Learning, American Politics.



# Social Links
social:
- {icon: "twitter", link: "https://twitter.com/dannycebanks"}
- {icon: "github", link: "https://github.com/danielEbanks"}


# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Research'
      url: '/ResearchProjects/'



#-------------------------------
# Contact Settings
contact:
  email: daniel.c.ebanks@gmail.com # Add your form_id
  description: Please feel free to reach out! 

# NOTE
# Mria theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id